title: Balbin Watches
description: > # this means to ignore newlines until "baseurl:"
  A fun and unique watchmaker based in the Philippines.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.balbinwatches.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Balbin Watches
author-img: balbin-logo.PNG
about-author: I am Jolo Balbin, an aspiring watchmaker based in the Philippines. I make unique and bespoke watches and consider them as an art piece.<br>Check out this website to see the wathces that I made. Some are also available!
social-twitter: # add your Twitter handle
social-facebook: https://www.facebook.com/profile.php?id=100093856061898
social-github: mojojolo # add your Github handle
social-instagram: https://www.instagram.com/balbinwatches
social-linkedin: # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
